### ISSUE TITLE
Migrate to hyper 0.12

### ISSUE THREAD

**Issue by fan-tom** [cretz/prost-twirp#1]
Consider migration to hyper 0.12 to get rid of deprecated tokio-core and other tokio crates and use https://github.com/tokio-rs/tokio instead

**Comment by cretz** [comment]
I'm afraid I no longer use this library and can't really justify maintaining it for my own use. I'll gladly accept a PR though or even transfer ownership. I probably should mark it unmaintained.

**Comment by sourcefrog** [comment]
I've made a new release 0.2.0 with current as of today dependencies:

* https://github.com/sourcefrog/prost-twirp/releases/tag/prost-twirp-0.2.0
* https://crates.io/crates/prost-twirp

**Comment by cretz** [comment]
Great! Updating README now.

**Comment by cretz** [comment]
Done. Will archive at a later date.
